name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

# concurrency:
#   group: ${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Set up Rust
        run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Install candid-extractor
        run: cargo install candid-extractor
      - name: Start dfx
        run: |
          dfx cache install
          dfx start --background
      - name: Deploying Canister
        run: npm run deploy:all
      - name: Generate Candid Declarations
        run: dfx generate
      - name: Install Node Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:all
